[CMOB-1708] Feature: Create Design
georgemakadze/QuizApp pull request #1
Opened 2023-06-03 07:28 UTC by georgemakadze

2023-06-12 09:28 UTC, MariamOrmotsadze requested changes

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +        popupLabel.textColor = .white
ფერები და ფონტები რომ კონსტანტებში გაიტანო არ იქნებოდა ურიგო

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +        popupScoreLabel.font = .systemFont(ofSize: Constants.PopupScoreLabel.font)
კონსტანტები

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +        dividerView.backgroundColor = .white
კონსტანტები

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +        closeButton.setTitle("დახურვა", for: .normal)
ტექსტიც კონსტანტებში უნდა იყოს

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +        view.backgroundColor = UIColor(white: 0, alpha: 0.5)
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +        enum PopupLabel {
ეს ძალიან სუბიექტურია, მაგრამ მე enum-ებს შორის გამოვტოვებდი ადგილებს
```suggestion
        }
        
        enum PopupLabel {
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/GPADetailViewController.swift
> +        pointLabel.backgroundColor = .clear
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/GPADetailViewController.swift
> +        //        noPointsImageConstraints()
კომენტარი გაქვს ჩარჩენილი

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/GPADetailViewController.swift
> +        return subjects.count
```suggestion
        subjects.count
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/GPADetailViewController.swift
> +
```suggestion

// MARK: - UITableViewDelegate
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +
```suggestion
    
    // MARK: - Components
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +
```suggestion

// MARK: - Constants
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +
ესეც ალბათ გემოვნებაზეა დამოკიდებული, მაგრამ setUp-ების ნაწილი ცალკე private extension-ში გამაქვს ხოლმე და აუცილებლად MARK: - Set Up-ით გამოვყოფ, თან თითოეულ ფუნქციაზე აღარ გჭირდება რომ private დაუწერო

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/GPADetailViewController.swift
> +
```suggestion

// MARK: - Properties    
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/GPADetailViewController.swift
> +
```suggestion
    
    // MARK: - Components
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/GPADetailViewController.swift
> +
```suggestion

// MARK: - UITableViewDataSource
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/GPADetailViewController.swift
> +
```suggestion

// MARK: - Constants
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/ScoreCell/ScoreCell.swift
> +
// MARK: - Components

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/ScoreCell/ScoreCell.swift
> +        nameLabel.textColor = .black
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/ScoreCell/ScoreCell.swift
> +        descriptionLabel.backgroundColor = .clear
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/ScoreCell/ScoreCell.swift
> +        scoreLabel.textColor = .white
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/ScoreCell/ScoreCell.swift
> +        scoreLabel.font = .systemFont(ofSize: Constants.ScoreLabel.font)
პირდაპირ ფონტი რომ გაიტანო კონსტანტებში და არა საიზი?

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/ScoreCell/ScoreCell.swift
> +            //firstLabel.bottomAnchor.constraint(equalTo: containerView.bottomAnchor, constant: -52)
ჩარჩენილი კომენტარი

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/ScoreCell/ScoreCell.swift
> +
```suggestion

// MARK: - Constants
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +
```suggestion
    
    // MARK: - Properties
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +
```suggestion
    
    // MARK: - Components
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +        gpaTextLabel.font = .systemFont(ofSize: Constants.GpaTextLabel.font)
ფონტზე იგივე აქაც, პირდაპირ ფონტის გატანა არ გამოდის?
(ბევრგანაა ასეთი და ყველგან არ დაგიკომენტარებ)

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +        gpaTextLabel.textColor = .white
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +        gpaScoreLabel.text = "1.0"
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +        scoreViewDetailLabel.backgroundColor = .clear
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +        gpaScoreLabel.backgroundColor = .clear
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +    }()
არ გერჩივნა რაღაც helper ფუნქცია გაგეკეთებინა? მაგალითად makeLabel, რომელსაც გადაეცემა ტექსტი, ფონტი, ტექსტის და თვითონ ლეიბლის ფერი? ყველგან მაგას გამოიყენებდი
+ lazy var რატომ არის ლეიბლები?

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +        chooseSubjectLabel.textColor = .black
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +        chooseSubjectLabel.backgroundColor = .clear
კოსნტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +        //
გჭირდება?

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +//}
?

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +
```suggestion

// MARK: - UITableViewDataSource
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +        return subjects.count
```suggestion
        subjects.count
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +//        cell.delegate = self
?

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +
```suggestion

// MARK: - UITableViewDelegate
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +        let distanceBetweenCells: CGFloat = 18
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +
```suggestion

// MARK: - Constants
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/TableViewCells/SubjectCell.swift
> +//}
?

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/TableViewCells/SubjectCell.swift
> +
```suggestion
    
    // MARK: - Components
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/TableViewCells/SubjectCell.swift
> +        nameLabel.textColor = .black
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/TableViewCells/SubjectCell.swift
> +        descriptionLabel.backgroundColor = .clear
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/TableViewCells/SubjectCell.swift
> +    //    weak var delegate: SubjectCellDelegate?
?

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/TableViewCells/SubjectCell.swift
> +    }
?

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/TableViewCells/SubjectCell.swift
> +            //            containerView.heightAnchor.constraint(equalToConstant: Constants.ContainerView.heightAnchor)
?

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/HomeViewController/TableViewCells/SubjectCell.swift
> +
```suggestion

// MARK: - Constants
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/PopupViewConstroller/PopupViewController.swift
> +
```suggestion
    
    // MARK: - Components
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/PopupViewConstroller/PopupViewController.swift
> +        popupLabel.backgroundColor = .clear
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/PopupViewConstroller/PopupViewController.swift
> +        popupLabel.textColor = .white
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/PopupViewConstroller/PopupViewController.swift
> +        yesButton.backgroundColor = .white
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/PopupViewConstroller/PopupViewController.swift
> +        noButton.backgroundColor = .white
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/PopupViewConstroller/PopupViewController.swift
> +
```suggestion

// Mark: - Constants
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/QuizController/AnswerCell/AnswerCell.swift
> +
```suggestion
    
    // Mark: - Components
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/QuizController/AnswerCell/AnswerCell.swift
> +        answerLabel.backgroundColor = .clear
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/QuizController/AnswerCell/AnswerCell.swift
> +        answerLabel.textColor = .black
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/QuizController/AnswerCell/AnswerCell.swift
> +
```suggestion

// Mark: - Constants
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/QuizController/QuizViewController.swift
> +
```suggestion
    
    // Mark: - Properties
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/QuizController/QuizViewController.swift
> +
```suggestion
    
        // Mark: - Components
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/QuizController/QuizViewController.swift
> +        questionLabel.backgroundColor = .clear
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/QuizController/QuizViewController.swift
> +        view.backgroundColor = .white
setUpViewსი გავიტანდი მე ამას + კონსტანტებში

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/QuizController/QuizViewController.swift
> +        //        cell.configure(with: question.answer)
?

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/QuizController/QuizViewController.swift
> +
```suggestion

// Mark: - UITableViewDataSource
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/QuizController/QuizViewController.swift
> +
```suggestion

// Mark: - UITableViewDelegate
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/QuizController/QuizViewController.swift
> +        let distanceBetweenCells: CGFloat = 12
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/QuizController/QuizViewController.swift
> +
```suggestion

// Mark: - Constants
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Extensions/UIColor+Extantions.swift
> +                  alpha: CGFloat(1.0))
line wrapping რეკომენდაციებს შეგიძლია გადახედო

```suggestion
      self.init(
        red: CGFloat((rgbValue & 0xFF0000) >> 16) / 255.0,
        green: CGFloat((rgbValue & 0x00FF00) >> 8) / 255.0,
        blue: CGFloat(rgbValue & 0x0000FF) / 255.0,
        alpha: CGFloat(1.0)
    )
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Scenes/Login/LoginViewController.swift
> +
```suggestion
    
    // Mark: - Components
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Scenes/Login/LoginViewController.swift
> +        loginTextView.backgroundColor = .clear
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Scenes/Login/LoginViewController.swift
> +        loginTextView.contentInset = UIEdgeInsets(top: 5, left: 1.0, bottom: 5, right: 1.0)
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Scenes/Login/LoginViewController.swift
> +        coverLabel.backgroundColor = .clear
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Scenes/Login/LoginViewController.swift
> +        coverLabel.textColor = .white
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Scenes/Login/LoginViewController.swift
> +        view.backgroundColor = .white
კონსტ

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Scenes/Login/LoginViewController.swift
> +        //        navigationController?.setNavigationBarHidden(true, animated: false)
?

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Scenes/Login/LoginViewController.swift
> +            //            coverIcon.bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: Constants.CoverIcon.bottomAnchor),
?

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Scenes/Login/LoginViewController.swift
> +
```suggestion

// Mark: - Constants
```

2023-06-12 09:28 UTC, MariamOrmotsadze commented on QuizApp/Scenes/Login/LoginViewController.swift
> +extension LoginViewController {
private extension?

2023-06-12 09:46 UTC, georgemakadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +        popupLabel.textColor = .white
static let fontSize: CGFloat = 16.0
static let font: UIFont = .systemFont(ofSize: fontSize) ამაზე მოკლე გზა არსებობს  ..systemFont(ofSize-ნად რომ გავიტანო კონსტანტებში?

2023-06-12 09:48 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +        popupLabel.textColor = .white
პირობითად systemFont(ofSize: 16) რომ გაიტანო პირდაპირ?

2023-06-12 09:50 UTC, georgemakadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +        popupLabel.textColor = .white
მიერორებს ვერ გამაქვს ეგრე

2023-06-12 09:52 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +        popupLabel.textColor = .white
მოგწერ

2023-06-12 12:08 UTC, georgemakadze commented on QuizApp/Core/Custom UI/GPADetailViewController/GPADetailViewController.swift
> +        //        noPointsImageConstraints()
ეს მჭირდება

2023-06-12 12:33 UTC, georgemakadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +        //
კი ეს მჭირდება

2023-06-12 13:26 UTC, georgemakadze commented on QuizApp/Core/Custom UI/HomeViewController/HomeViewController.swift
> +    }()
კი ეს მერე ლოგიკებზე რომ გადავალ უნდა გავაკეთო(იმის მიხედვით თუ რამდენი ქულა დააგროვა იუზერმა)

2023-06-12 13:27 UTC, georgemakadze commented on QuizApp/Core/Custom UI/QuizController/QuizViewController.swift
> +        view.backgroundColor = .white
მხოლოდ ფერს ვუსეტავ და ამიტომ ვარჩიე ასე გამოძახება ფუნქციის გარეშე(კონსტანტებში გავიტანე)

2023-06-12 13:29 UTC, georgemakadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +
უბრალოდ ასე უფრო მარტივია ჩემთვის და ამიტომ ვარციე ასე ჩაწერა :D

2023-06-13 06:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +        closeButton.setTitle(Constants.CloseButton.setTitle, for: .normal)
შეგიძია არ შეცვალო, მაგრამ title უკეთესი სახელი იქნებოდა
```suggestion
        closeButton.setTitle(Constants.CloseButton.title, for: .normal)
```

2023-06-13 06:28 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +        closeButton.setTitleColor(Constants.CloseButton.setTitleColor, for: .normal)
```suggestion
        closeButton.setTitleColor(Constants.CloseButton.tiitleColor, for: .normal)
```

2023-06-13 06:36 UTC, MariamOrmotsadze requested changes

2023-06-13 06:36 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +            static let textColor: UIColor = .white
```suggestion
            static let backgroundColor = .clear
            static let textColor = .white
```

2023-06-13 06:36 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +            static let font: UIFont = .systemFont(ofSize: 18)
```suggestion
            static let font = .systemFont(ofSize: 18)
```

2023-06-13 06:36 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +            static let setTitleColor: UIColor = .white
```suggestion
            static let setTitleColor = .white
```

2023-06-13 06:36 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +            static let backgroundColor: UIColor = .clear
```suggestion
            static let backgroundColor = .clear
```

2023-06-13 06:36 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +            static let backgroundColor: UIColor = .clear
```suggestion
            static let backgroundColor = .clear
```

2023-06-13 06:36 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +            static let font: UIFont = .systemFont(ofSize: 18)
```suggestion
            static let font = .systemFont(ofSize: 18)
```

2023-06-13 06:36 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +            static let backgroundColor: UIColor = UIColor(white: 0, alpha: 0.5)
```suggestion
            static let backgroundColor = UIColor(white: 0, alpha: 0.5)
```

2023-06-13 06:36 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +            static let backgroundColor: UIColor = .white
```suggestion
            static let backgroundColor = .white
```

2023-06-13 06:36 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/GPADetailViewController.swift
> +
ეს ძალიან ინდივიდუალურია, მე მაგალითად მარკების შემდეგ არ ვტოვებ ხაზებს; ამაზე ვერაფერს ვერ გეტყვი, უბრალოდ ერთი სტილი აირჩიე, თუ გადაწყვეტ რომ მარკების შემდეგ ხაზები გამოტოვო, ყველგან ეგრე დაწერე, თუ გადაწყვეტ რომ არ გამოტოვო, მაშინ აქაც წაშალე. სხვა ადგილებსი შემხვდა რომ არ გქონდა ხაზი გამოტოვებული და მაგიტომ გიკომენტარებ ამას.

```suggestion
```

2023-06-13 06:36 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/GPADetailViewController.swift
> +            static let textColor: UIColor  = .black
```suggestion
            static let textColor  = .black
```

2023-06-13 06:36 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/GPADetailViewController.swift
> +            static let font: UIFont = .systemFont(ofSize: 16)
აღარ დაგიკომენტარებ ყველგან ამას, redundant ცვლადის ტიპები მოაშორე, არაა საჭირო
```suggestion
            static let font = .systemFont(ofSize: 16)
```

2023-06-13 06:36 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/GPADetailViewController/ScoreCell/ScoreCell.swift
> +
ამეებზეც აღარ დაგიკომენტარებ, გადაწყვიტე რომელი მიდგომით გაუყვები და ყველგან შესაბამისად შეცვალე
```suggestion
```

2023-06-13 06:36 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/PopupViewConstroller/PopupViewController.swift
> +    private lazy var popupLabel: UILabel = {
ეს lazy რატომაა? ბევრგან გაქვს ასე

2023-06-13 08:14 UTC, georgemakadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +            static let textColor: UIColor = .white
<img width="978" alt="Screenshot 2023-06-13 at 12 13 04" src="https://github.com/georgemakadze/QuizApp/assets/111285282/7fdf11a3-7768-4965-b997-d00b2d7e742d">
როგორ მოვიქცე?

2023-06-13 08:16 UTC, georgemakadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +            static let font: UIFont = .systemFont(ofSize: 18)
<img width="1009" alt="Screenshot 2023-06-13 at 12 15 55" src="https://github.com/georgemakadze/QuizApp/assets/111285282/ec67482b-d31d-40d9-b17c-3285ed72e482">
აქაც იგივე პრობლემა მაქვს

2023-06-13 08:36 UTC, georgemakadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +            static let textColor: UIColor = .white
<img width="745" alt="Screenshot 2023-06-13 at 12 34 29" src="https://github.com/georgemakadze/QuizApp/assets/111285282/c73d23df-840c-4d2f-8527-8840e8f3dc7f">
ან შეიძლება ასე ჩაიწეროს სხვა გზა ვერ მოვძებნე

2023-06-13 08:36 UTC, georgemakadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +            static let font: UIFont = .systemFont(ofSize: 18)
<img width="544" alt="Screenshot 2023-06-13 at 12 34 56" src="https://github.com/georgemakadze/QuizApp/assets/111285282/6f21d2b8-d396-48da-9447-bc96b50224bd">
აქაც იგივენაირად

2023-06-13 09:50 UTC, georgemakadze commented on QuizApp/Core/Custom UI/PopupViewConstroller/PopupViewController.swift
> +    private lazy var popupLabel: UILabel = {
თავიდან მქონდა ცალკე ფუნქციებში გატანილი და ვიძახებდი viewdidload-ში. მაგ(private var coverImageView: UIImageView!

private func setupCoverImageView() {
    coverImageView = UIImageView()
    coverImageView.image = Constants.CoverImageView.image
    coverImageView.contentMode = .scaleAspectFill
    view.addSubview(coverImageView)
    coverImageView.translatesAutoresizingMaskIntoConstraints = false
})წინა პროექტის  რევიუზე მითხრეს რომ closure-ბით ჩამეწერა ამიტომ გადავაკეთე. როცა private let -ით ვაცხადებდი მქონდა ერორი რომელსაც ვერ ვფიქსავდი მაგ: 
<img width="1061" alt="Screenshot 2023-06-13 at 13 38 08" src="https://github.com/georgemakadze/QuizApp/assets/111285282/eb31aaec-81db-4eff-9093-1cacce827a98">
ამიტომ ერთადერთი სოლუშენი რაც ვნახე მარტივად ამის დასაფიქსად იყო closure-ს lazy var-დ ჩაწერა. თორემ იდეაში lazy var-ებით მხოლოდ სელები უნდა ჩამეწერა,  მხოლოდ იმ შემთხვევაში გამოძახებულიყო როცა საჭიროება იქნებოდა, მაგრამ ყველაზე მომიწია ამის გაწერა იმიტომ რომ სხვა უფრო უკეთეს სოლუშენს ვერ მივაგენი

2023-06-13 10:49 UTC, georgemakadze commented on QuizApp/Core/Custom UI/PopupViewConstroller/PopupViewController.swift
> +    private lazy var popupLabel: UILabel = {
მეორე გზა ვნახე ამის მოსაგვარებლად, addSubview ქონსთრეინთებში რომ გავიტანო
<img width="918" alt="Screenshot 2023-06-13 at 14 46 23" src="https://github.com/georgemakadze/QuizApp/assets/111285282/f1102782-17a4-4ee7-825e-73f15c1e4c06">
და მერე როცა private let- ბად გადავაკეთე არ დამიერორა. რას ფიქრობ როგორ მოვიქცე?

2023-06-14 06:12 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/PopupViewConstroller/PopupViewController.swift
> +    private lazy var popupLabel: UILabel = {
კი let უნდა იყოს და სეტაპში დაამატო, კაია

2023-06-14 06:13 UTC, MariamOrmotsadze commented on QuizApp/Core/Custom UI/FinishPopup/FinishPopupController.swift
> +            static let textColor: UIColor = .white
არ შეცვალო მაშინ ეგენი, აზრი არ აქვს, წავსი ამ კომენტარებს

2023-06-14 06:13 UTC, MariamOrmotsadze approved these changes

2023-06-16 13:18 UTC, LiziChichua requested changes
ვნახე რამდენიმე ვიზუალური ბაგიც. ჩამოგიწერ და გაასწორე. დანარჩენი კომენტარები კოდში მიგიწერე

1 - LoginViewController ში რომ ტექსტფილდია მაგას აქვს ვიზუალური ბაგი

https://github.com/georgemakadze/QuizApp/assets/83401753/be8068eb-a08c-48de-9667-d800dc3d57c4

2 - HomeViewController ში გაკლია "გამარჯობა, ირაკლი" ტექსტი

ესეთი უნდა იყოს:
<img width="254" alt="Screenshot 2023-06-16 at 5 14 25 PM" src="https://github.com/georgemakadze/QuizApp/assets/83401753/e4bffb65-0b20-4eac-bb39-e50ec1edf674">

არის ესეთი:
<img width="374" alt="Screenshot 2023-06-16 at 5 14 32 PM" src="https://github.com/georgemakadze/QuizApp/assets/83401753/b4c380dc-cdc5-43ba-b4cd-cc92fa822c03">


3 - GPADetailViewController იც არ შეესაბამება დიზაინს. ნავიგაციას დააკვირდი
უნდა იყოს:
<img width="257" alt="Screenshot 2023-06-16 at 5 16 21 PM" src="https://github.com/georgemakadze/QuizApp/assets/83401753/cd035a1b-8b45-44b7-8032-07dd7674591f">

არის ესეთი:
<img width="373" alt="Screenshot 2023-06-16 at 5 16 27 PM" src="https://github.com/georgemakadze/QuizApp/assets/83401753/54c23d77-f7c5-46ca-a5a9-d2cff2756495">

+ აქ LogOut ის ღილაკიც არ გაქვს (დიზაინში არის)

2023-06-16 13:18 UTC, LiziChichua commented on QuizApp.xcodeproj/project.pbxproj
> +				0EDD08DB2A3B21FF00FF282B /* TableViewCells */,
`Custom UI` ფოლდერში არ უნდა გქონდეს `TableViewCells` ფოლდერი. თუ მაგალითად `SubjectCell` ეკუთვნის `HomeViewController` ს მაშინ ეს სელი `Scenes` ფოლდერში რომ `Home` ფოლდერი გექნება მანდ უნდა დაამატო ჯერ `TableViewCell` ფოლდერი და აქ უნდა ჩასვა ეგ სელი

2023-06-16 13:18 UTC, LiziChichua commented on QuizApp.xcodeproj/project.pbxproj
> +				0EDD08DB2A3B21FF00FF282B /* TableViewCells */,
იგივე ეხება `ScoreCell` საც და `AnswerCell`

2023-06-16 13:18 UTC, LiziChichua commented on QuizApp/Scenes/HomeViewController/HomeViewController.swift
> +//    private lazy var scoreViewDetailButton:  = {
რატომ გაქვს ჩაკომენტარებული? თუ არ იყენებ წაშალე

2023-06-16 13:18 UTC, LiziChichua commented on QuizApp/Scenes/HomeViewController/HomeViewController.swift
> +        cell.selectionStyle = .none
`selectionStyle` ის დასეტვა სელში გაიტანე

2023-06-16 13:18 UTC, LiziChichua commented on QuizApp/Scenes/GPADetailViewController/GPADetailViewController.swift
> +        //        noPointsImageConstraints()
თუ არ იყენებ წაშალე 67-ე ხაზი

2023-06-16 13:18 UTC, LiziChichua commented on QuizApp/Scenes/GPADetailViewController/GPADetailViewController.swift
> +        cell.selectionStyle = .none
`selectionStyle` ის დასეტვა სელში გაიტანე

2023-06-16 13:18 UTC, LiziChichua commented on QuizApp/Scenes/QuizController/QuizViewController.swift
> +        // daklikeba
წაშალე ეს კომენტარი

2023-06-16 13:18 UTC, LiziChichua commented on QuizApp/Scenes/QuizController/QuizViewController.swift
> +
150 - 151 ხაზები წაშალე

2023-06-16 13:18 UTC, LiziChichua commented on QuizApp/Scenes/QuizController/QuizViewController.swift
> +        cell.selectionStyle = .none
იგივე

2023-06-16 13:18 UTC, LiziChichua commented on QuizApp/Scenes/QuizController/QuizViewController.swift
> +
მარკი დაადე // MARK: - PopupViewControllerDelegate

2023-06-16 13:18 UTC, LiziChichua commented on QuizApp/Scenes/QuizController/QuizViewController.swift
> +
აქაც მარკი FinishPopupControllerDelegate სთვის

2023-06-16 13:18 UTC, LiziChichua commented on QuizApp/Scenes/QuizController/QuizViewController.swift
> +    func setupNavigationController() {
`setupNavigationController` ფუნქცია `nextButtonTapped` ფუნქციის თავზე აიტანე და მერე `nextButtonTapped` და `rightBarButtonTapped` ფუნქცია ერთად გექნება. ესე უფრო სწორი იმიტომ რომ შინაარსობრივად ექშენ ფუნქციები ერთად დალაგდება + მარკიც დაადე ექშენ ფუქნციებს

2023-06-16 13:18 UTC, LiziChichua commented on QuizApp/Scenes/HomeViewController/HomeViewController.swift
> +
მარკი დაადე

2023-06-16 13:18 UTC, LiziChichua commented on QuizApp.xcodeproj/project.pbxproj
>  		0EDD08AA2A2A0B5000FF282B /* Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = Info.plist; sourceTree = "<group>"; };
`Info` ფაილიდ გაიტანე `SupportingFiles` ფოლდერში (წინაზე როგორც გაგაკეთებინე ეგრე)

2023-06-16 13:18 UTC, LiziChichua commented on QuizApp.xcodeproj/project.pbxproj
>  				0EDD08A22A2A0B4E00FF282B /* QuizApp.xcdatamodeld */,
ქორდატას მოდელის ფაილიც გაიტანე `Core` ფოლდერში. `Core` -> `CoreData` -> QuizApp.xcdatamodeld

2023-06-28 13:29 UTC, LiziChichua requested changes

2023-06-28 13:29 UTC, LiziChichua commented on QuizApp/Core/Custom UI/GPA/GPAView.swift
> +            super.init(frame: .zero)
ინდენტაცია გაასწორე

2023-06-28 13:29 UTC, LiziChichua commented on QuizApp/Core/Models/Question.swift
> +struct Question: Hashable {
რატომ `Hashable`?

2023-06-28 13:29 UTC, LiziChichua commented on QuizApp/Core/Models/Subject.swift
> +struct Subject: Hashable {
იგივე

2023-06-28 13:29 UTC, LiziChichua commented on QuizApp/Core/Models/SubjectResult.swift
> +struct SubjectResult: Hashable {
იგივე

2023-06-28 13:29 UTC, LiziChichua commented on QuizApp/Core/Custom UI/LogOutPopup/PopupViewController.swift
> +    func didTapYesButton()
დელეგატში აუცილებლად გასათვალისწინებელი გაქვს ის შემთხვევაც როდესაც No ღილაკს დააჭერს თითს

2023-06-28 13:29 UTC, LiziChichua commented on QuizApp/Scenes/Quiz/ViewModel/QuizViewModel.swift
> +        return  "მიმდინარე ქულა - \(correctAnswer)⭐️"
`return` წაუშალე საერთოდ

2023-06-28 13:29 UTC, LiziChichua commented on QuizApp/Scenes/Quiz/ViewModel/QuizViewModel.swift
> +          let correctAnswer = questions[currentQuestionIndex].correctAnswer
ინდენტაცია გაასწორე

2023-06-28 13:29 UTC, LiziChichua commented on QuizApp/Scenes/Quiz/QuizViewController.swift
> +
ერთი ხაზი გაქ ზედმეტი აქ და წაშალე

2023-06-28 13:29 UTC, LiziChichua commented on QuizApp/Scenes/Quiz/QuizViewController.swift
> +        navigationItem.title = "პროგრამირება"
კონსტანტები

2023-06-28 13:29 UTC, LiziChichua commented on QuizApp/Scenes/Login/LoginViewController.swift
> +        super.viewDidLoad()
`viewDidLoad` ის ტანი გაქვს გადატვრთული, ფუნქციებად ჩაშალე

2023-06-28 13:29 UTC, LiziChichua commented on QuizApp/Scenes/Login/LoginViewController.swift
> +class LoginViewController: UIViewController {
ფლეისჰოლდერის ბაგი გაფიქსე

2023-06-29 07:42 UTC, georgemakadze commented on QuizApp/Core/Models/Question.swift
> +struct Question: Hashable {
წინა პროექტის მიხედვით ავაწყე აქაც მოდელები, აქ არ მჭირდება ნამდვილად, წინაში UICollectionViewDiffableDataSource-ს სჭირდებოდა და ამიტომ გამოვიყენე.

2023-06-29 08:08 UTC, LiziChichua approved these changes

2023-06-29 08:12 UTC, merged